### ISSUE TITLE
Support QQ Group message receive & send

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-oicq#13]
If we use Wechaty to manage our QQ group, we need to support the QQ group message receiving & sending.

Reference source code:

https://github.com/wechaty/wechaty-puppet-wechat/blob/a45a4ab7e20bb9cfc328e904966a550dbdc8e3a0/src/pure-function-helpers/message-raw-payload-parser.ts#L21-L41

Link to

- #12

**Comment by huan** [comment]
`messageSendText(conversationId, text)` is using for both Contact.say and Room.say.

Please refer to the below example code and feel free to let me know your questions by replying this issue.

## Send room message code example

1. Wechaty Room source code at [here](https://github.com/wechaty/wechaty/blob/935fecb96915aaa75667e27b4c401d9c8cd32680/src/user/room.ts#L519-L523)
2. Puppet Wechaty messageSendText source code at [here](https://github.com/wechaty/puppet-wechat/blob/3e231865a041b520370cd009cb924fcb96b3e5b5/src/puppet-wechat.ts#L507-L515)

**Comment by anaivebird** [comment]
If someone say message in group, and he is not a friend of the bot. `contactRawPayload` could not find contact info from `this.contactStore`.

To fix this problem. We will add a person's info to `this.contactStore` after he says something in group if he is not a friend of bot.

**Comment by anaivebird** [comment]
Group ding dong succeeded!

> how to tell Room.say from Contact.say, since QQ group number and QQ account number can be same?
> Have you got the solutions to it? Our current design in Puppet API is using a conversationId for both contact and room.

Currently, the puppet will check if conversationId is in bot account's added group list. If bot has join group of conversationId, it will send the message to the group. Otherwise, a private message will be sent to qq of conversationId.
![image](https://user-images.githubusercontent.com/29398611/137623240-68a5560e-3974-4117-91c9-64f891f6403a.png)

**Comment by huan** [comment]
Congratulations!

Could you please help us to confirm the QQ account provided by @krapnikkk can work with our QQ ding/dong bot?

If we can have the QQ account worked, then I believe we can try to integrate our Friday BOT with QQ soon!

> Currently, the puppet will check if a conversation is in the bot account's added group list. If the bot has joined the group of conversationId, it will send the message to the group. Otherwise, a private message will be sent to QQ of conversationId.

It's a good workaround. I hope we can find a way to deal with it better in the future.
